/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;



public class App {
    public static void main(String[] args) {
        System.out.println("API Testing Application Of Laizer");
    }
}
